# Generated by Django 6.0.1 on 2026-01-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailjetsettings',
            name='from_email',
            field=models.EmailField(default='contact@shaznuz.com', max_length=254),
        ),
    ]
